export const languages = [
  { id: 'en', label: 'English', short: 'EN' },
  { id: 'hi', label: 'Hindi', short: 'HI' },
  { id: 'gu', label: 'Gujarati', short: 'GU' }
] as const;

export const copy = {
  en: {
    // Navigation & Layout
    home: 'Home',
    categories: 'Categories',
    saved: 'Saved',
    profile: 'Profile',
    sellItem: 'Sell item',
    searchMain: 'Search products, sellers, and neighborhoods',
    explore: 'Explore',
    account: 'Account',
    productDetails: 'Product Details',

    // MarketplacePage
    nationalSuperApp: 'National super app',
    marketplaceFeedDesc: 'Marketplace feed for everything local.',
    marketplaceSubDesc: 'Products, vehicles, property, rentals, services, jobs, and local professionals in one clean discovery experience.',
    viewAllCategories: 'View all categories',
    searchCategoryOrProduct: 'Search category or product',
    saves: 'saves',
    showLess: 'show less',
    readMore: 'read more',

    // ProductFilters
    searchPlaceholder: 'Search iPhone, sofa, bike...',
    newestFirst: 'Newest first',
    mostPopular: 'Most popular',
    priceAsc: 'Price: low to high',
    priceDesc: 'Price: high to low',
    all: 'All',

    // CategoriesPage
    categoryDirectory: 'Category directory',
    allCategories: 'All Categories',
    categoriesDesc: 'Pick a section and go straight to the listings that match what you want to buy, rent, or book.',
    sections: 'sections',
    listAnItem: 'List an item',
    searchCategories: 'Search category...',
    categoriesAvailable: 'categories available',

    // SellPage & ProductForm
    creatorStudio: 'Creator studio',
    createListing: 'Create listing',
    createListingDesc: 'Add clean photos, honest details, and pricing that helps buyers trust your listing instantly.',
    title: 'Title',
    titlePlaceholder: 'Apple Studio Display, walnut desk, road bike...',
    price: 'Price',
    location: 'Location',
    locationPlaceholder: 'Brooklyn, NY',
    category: 'Category',
    condition: 'Condition',
    description: 'Description',
    descriptionPlaceholder: 'Tell buyers what matters: condition, included accessories, pickup options.',
    uploadPhotos: 'Upload photos',
    maxPhotos: 'Add up to 3 photos. First photo becomes the cover.',
    performanceTips: 'Performance tips',
    tip1: 'Use bright 4:5 photos for better feed reach.',
    tip2: 'Keep title short and searchable.',
    tip3: 'Upload compressed images for old mobile devices.',
    publish: 'Publish listing',
    pleaseUpload3: 'Please upload exactly 3 photos.',
    cover: 'Cover',
    add: 'Add',

    // DashboardPage
    sellerProfile: 'Seller profile',
    settings: 'Settings',
    activeListings: 'Active listings',
    profileViews: 'Profile views',
    rating: 'Rating',
    verifiedSeller: 'Verified seller. Premium gadgets, furniture, vehicles and local deals. Fast replies, clean handovers.',
    kycVerified: 'KYC verified',
    topSeller: 'Top seller',
    editProfile: 'Edit profile',
    addListing: 'Add listing',
    email: 'Email',
    phone: 'Phone',
    trust: 'Trust',
    identityVerified: 'Identity verified',
    language: 'Language',
    inventory: 'Inventory',
    yourListings: 'Your listings',
    listings: 'Listings',

    // WishlistPage
    savedCollection: 'Saved collection',
    savedProducts: 'Saved products',
    savedProductsDesc: 'Keep your shortlisted listings organized so you can compare price, seller and location quickly.',
    savedItems: 'saved items',
    noSavedListings: 'No saved listings yet',
    noSavedDesc: 'Tap the heart on any product to keep it close.',
    featured: 'Featured',
    viewDetails: 'View details',

    // ProductDetailPage
    listingUnavailable: 'Listing unavailable',
    backToMarketplace: 'Back to marketplace',
    whatsappSeller: 'WhatsApp seller',
    saveListing: 'Save listing',
    share: 'Share',
    sellerRating: 'seller rating',
    identitySignalsVerified: 'Identity and payment signals verified',

    // MessagesPage
    chat: 'Chat',
    searchChat: 'Search chat...',
    now: 'Now',
    online: 'Online',
    today: 'Today',
    writeMessage: 'Write a message...',

    // AuthPage
    yourTrustedAccount: 'Your trusted local marketplace account.',
    authDesc: 'Save listings, message sellers, manage inventory, and build a reputation buyers can trust.',
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    authSubDesc: 'Firebase email/password and Google auth are wired in.',
    fullName: 'Full name',
    emailAddress: 'Email address',
    password: 'Password',
    signIn: 'Sign in',
    continueWithGoogle: 'Continue with Google',
    needAccount: 'Need an account?',
    alreadyHaveAccount: 'Already have an account?',
    mobileNumber: 'Mobile Number',
    memberSince: 'Member Since',
  },
  hi: {
    home: 'होम',
    categories: 'श्रेणियां',
    saved: 'सहेजे गए',
    profile: 'प्रोफ़ाइल',
    sellItem: 'सामान बेचें',
    searchMain: 'उत्पाद, विक्रेता और पड़ोस खोजें',
    explore: 'एक्सप्लोर करें',
    account: 'खाता',
    productDetails: 'उत्पाद विवरण',
    nationalSuperApp: 'राष्ट्रीय सुपर ऐप',
    marketplaceFeedDesc: 'हर स्थानीय चीज़ के लिए मार्केटप्लेस फ़ीड।',
    marketplaceSubDesc: 'उत्पाद, वाहन, संपत्ति, किराये, सेवाएँ, नौकरियाँ और स्थानीय पेशेवर एक स्पष्ट खोज अनुभव में।',
    viewAllCategories: 'सभी श्रेणियां देखें',
    searchCategoryOrProduct: 'श्रेणी या उत्पाद खोजें',
    saves: 'सेव्स',
    showLess: 'कम दिखाएं',
    readMore: 'और पढ़ें',
    searchPlaceholder: 'iPhone, सोफा, बाइक खोजें...',
    newestFirst: 'सबसे नया पहले',
    mostPopular: 'सबसे लोकप्रिय',
    priceAsc: 'कीमत: कम से अधिक',
    priceDesc: 'कीमत: अधिक से कम',
    all: 'सभी',
    categoryDirectory: 'श्रेणी निर्देशिका',
    allCategories: 'सभी श्रेणियां',
    categoriesDesc: 'एक अनुभाग चुनें और सीधे उन लिस्टिंग पर जाएं जो आप खरीदना, किराए पर लेना या बुक करना चाहते हैं।',
    sections: 'अनुभाग',
    listAnItem: 'सामान सूचीबद्ध करें',
    searchCategories: 'श्रेणी खोजें...',
    categoriesAvailable: 'श्रेणियां उपलब्ध हैं',
    creatorStudio: 'क्रिएटर स्टूडियो',
    createListing: 'लिस्टिंग बनाएं',
    createListingDesc: 'साफ़ फ़ोटो, ईमानदार विवरण और मूल्य निर्धारण जोड़ें जो खरीदारों को आपकी लिस्टिंग पर तुरंत भरोसा करने में मदद करे।',
    title: 'शीर्षक',
    titlePlaceholder: 'Apple Studio Display, अखरोट की मेज, रोड बाइक...',
    price: 'कीमत',
    location: 'स्थान',
    locationPlaceholder: 'मुंबई, महाराष्ट्र',
    category: 'श्रेणी',
    condition: 'स्थिति',
    description: 'विवरण',
    descriptionPlaceholder: 'खरीदारों को बताएं कि क्या मायने रखता है: स्थिति, शामिल सहायक उपकरण, पिकअप विकल्प।',
    uploadPhotos: 'तस्वीरें अपलोड करें',
    maxPhotos: '3 तस्वीरें तक जोड़ें। पहली तस्वीर कवर बन जाएगी।',
    performanceTips: 'प्रदर्शन सुझाव',
    tip1: 'बेहतर फ़ीड पहुंच के लिए उज्ज्वल 4:5 तस्वीरों का उपयोग करें।',
    tip2: 'शीर्षक छोटा और खोजने योग्य रखें।',
    tip3: 'पुराने मोबाइल उपकरणों के लिए संकुचित चित्र अपलोड करें।',
    publish: 'लिस्टिंग प्रकाशित करें',
    pleaseUpload3: 'कृपया ठीक 3 तस्वीरें अपलोड करें।',
    cover: 'कवर',
    add: 'जोड़ें',
    sellerProfile: 'विक्रेता प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    activeListings: 'सक्रिय लिस्टिंग',
    profileViews: 'प्रोफ़ाइल दृश्य',
    rating: 'रेटिंग',
    verifiedSeller: 'सत्यापित विक्रेता। प्रीमियम गैजेट, फर्नीचर, वाहन और स्थानीय सौदे। तेज़ उत्तर, साफ़ हैंडओवर।',
    kycVerified: 'KYC सत्यापित',
    topSeller: 'शीर्ष विक्रेता',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    addListing: 'लिस्टिंग जोड़ें',
    email: 'ईमेल',
    phone: 'फ़ोन',
    trust: 'विश्वास',
    identityVerified: 'पहचान सत्यापित',
    language: 'भाषा',
    inventory: 'इन्वेंट्री',
    yourListings: 'आपकी लिस्टिंग',
    listings: 'लिस्टिंग',
    savedCollection: 'सहेजा गया संग्रह',
    savedProducts: 'सहेजे गए उत्पाद',
    savedProductsDesc: 'अपनी शॉर्टलिस्ट की गई लिस्टिंग को व्यवस्थित रखें ताकि आप कीमत, विक्रेता और स्थान की शीघ्रता से तुलना कर सकें।',
    savedItems: 'सहेजे गए आइटम',
    noSavedListings: 'अभी तक कोई सहेजी गई लिस्टिंग नहीं',
    noSavedDesc: 'किसी भी उत्पाद को पास रखने के लिए उस पर दिल पर टैप करें।',
    featured: 'विशेष',
    viewDetails: 'विवरण देखें',
    listingUnavailable: 'लिस्टिंग अनुपलब्ध',
    backToMarketplace: 'मार्केटप्लेस पर वापस जाएं',
    whatsappSeller: 'व्हाट्सएप विक्रेता',
    saveListing: 'लिस्टिंग सहेजें',
    share: 'शेयर करें',
    sellerRating: 'विक्रेता रेटिंग',
    identitySignalsVerified: 'पहचान और भुगतान संकेत सत्यापित',
    chat: 'चैट',
    searchChat: 'चैट खोजें...',
    now: 'अभी',
    online: 'ऑनलाइन',
    today: 'आज',
    writeMessage: 'एक संदेश लिखें...',
    yourTrustedAccount: 'आपका विश्वसनीय स्थानीय मार्केटप्लेस खाता।',
    authDesc: 'लिस्टिंग सहेजें, विक्रेताओं को संदेश भेजें, इन्वेंट्री प्रबंधित करें, और ऐसी प्रतिष्ठा बनाएं जिस पर खरीदार भरोसा कर सकें।',
    welcomeBack: 'वापसी पर स्वागत है',
    createAccount: 'खाता बनाएं',
    authSubDesc: 'Firebase ईमेल/पासवर्ड और Google प्रामाणिकता जुड़ी हुई है।',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    signIn: 'साइन इन करें',
    continueWithGoogle: 'Google के साथ जारी रखें',
    needAccount: 'क्या आपको एक खाते की आवश्यकता है?',
    alreadyHaveAccount: 'क्या आपके पास पहले से ही खाता है?',
    mobileNumber: 'मोबाइल नंबर',
    memberSince: 'सदस्यता शुरू:',
  },
  gu: {
    home: 'હોમ',
    categories: 'કેટેગરીઝ',
    saved: 'સાચવેલ',
    profile: 'પ્રોફાઇલ',
    sellItem: 'વસ્તુ વેચો',
    searchMain: 'ઉત્પાદનો, વેચાણકર્તાઓ અને પડોશ શોધો',
    explore: 'એક્સપ્લોર',
    account: 'એકાઉન્ટ',
    productDetails: 'ઉત્પાદન વિગતો',
    nationalSuperApp: 'રાષ્ટ્રીય સુપર એપ',
    marketplaceFeedDesc: 'દરેક સ્થાનિક વસ્તુ માટે માર્કેટપ્લેસ ફીડ.',
    marketplaceSubDesc: 'ઉત્પાદનો, વાહનો, સંપત્તિ, ભાડાં, સેવાઓ, નોકરીઓ અને સ્થાનિક વ્યાવસાયિકો એક સ્પષ્ટ શોધ અનુભવમાં.',
    viewAllCategories: 'બધી કેટેગરીઝ જુઓ',
    searchCategoryOrProduct: 'કેટેગરી અથવા ઉત્પાદન શોધો',
    saves: 'સેવ્સ',
    showLess: 'ઓછું બતાવો',
    readMore: 'વધુ વાંચો',
    searchPlaceholder: 'iPhone, સોફા, બાઇક શોધો...',
    newestFirst: 'સૌથી નવું પહેલા',
    mostPopular: 'સૌથી લોકપ્રિય',
    priceAsc: 'કિંમત: ઓછાથી વધુ',
    priceDesc: 'કિંમત: વધુથી ઓછી',
    all: 'બધા',
    categoryDirectory: 'કેટેગરી ડિરેક્ટરી',
    allCategories: 'બધી કેટેગરીઝ',
    categoriesDesc: 'એક વિભાગ પસંદ કરો અને સીધા તે લિસ્ટિંગ પર જાઓ જે તમે ખરીદવા, ભાડે લેવા અથવા બુક કરવા માંગો છો.',
    sections: 'વિભાગો',
    listAnItem: 'વસ્તુની નોંધણી કરો',
    searchCategories: 'કેટેગરી શોધો...',
    categoriesAvailable: 'કેટેગરીઝ ઉપલબ્ધ છે',
    creatorStudio: 'ક્રિએટર સ્ટુડિયો',
    createListing: 'લિસ્ટિંગ બનાવો',
    createListingDesc: 'સ્પષ્ટ ફોટા, પ્રમાણિક વિગતો અને કિંમત ઉમેરો જે ખરીદદારોને તરત જ તમારી લિસ્ટિંગ પર વિશ્વાસ કરવામાં મદદ કરે.',
    title: 'શીર્ષક',
    titlePlaceholder: 'Apple Studio Display, અખરોટનું ટેબલ, રોડ બાઇક...',
    price: 'કિંમત',
    location: 'સ્થાન',
    locationPlaceholder: 'અમદાવાદ, ગુજરાત',
    category: 'કેટેગરી',
    condition: 'સ્થિતિ',
    description: 'વર્ણન',
    descriptionPlaceholder: 'ખરીદદારોને જણાવો કે શું મહત્વનું છે: સ્થિતિ, શામેલ એસેસરીઝ, પિકઅપ વિકલ્પો.',
    uploadPhotos: 'ફોટા અપલોડ કરો',
    maxPhotos: '3 ફોટા સુધી ઉમેરો. પહેલો ફોટો કવર બનશે.',
    performanceTips: 'પ્રદર્શન ટિપ્સ',
    tip1: 'વધુ સારી ફીડ પહોંચ માટે તેજસ્વી 4:5 ફોટાનો ઉપયોગ કરો.',
    tip2: 'શીર્ષક ટૂંકું અને શોધી શકાય તેવું રાખો.',
    tip3: 'જૂના મોબાઇલ ઉપકરણો માટે સંકુચિત છબીઓ અપલોડ કરો.',
    publish: 'લિસ્ટિંગ પ્રકાશિત કરો',
    pleaseUpload3: 'કૃપા કરીને બરાબર 3 ફોટા અપલોડ કરો.',
    cover: 'કવર',
    add: 'ઉમેરો',
    sellerProfile: 'વેચાણકર્તા પ્રોફાઇલ',
    settings: 'સેટિંગ્સ',
    activeListings: 'સક્રિય લિસ્ટિંગ',
    profileViews: 'પ્રોફાઇલ દૃશ્યો',
    rating: 'રેટિંગ',
    verifiedSeller: 'ચકાસાયેલ વેચાણકર્તા. પ્રીમિયમ ગેજેટ્સ, ફર્નિચર, વાહનો અને સ્થાનિક ડીલ્સ. ઝડપી જવાબો, સ્વચ્છ હેન્ડઓવર.',
    kycVerified: 'KYC ચકાસાયેલ',
    topSeller: 'ટોચના વેચાણકર્તા',
    editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
    addListing: 'લિસ્ટિંગ ઉમેરો',
    email: 'ઇમેઇલ',
    phone: 'ફોન',
    trust: 'વિશ્વાસ',
    identityVerified: 'ઓળખ ચકાસાયેલ',
    language: 'ભાષા',
    inventory: 'ઇન્વેન્ટરી',
    yourListings: 'તમારી લિસ્ટિંગ',
    listings: 'લિસ્ટિંગ',
    savedCollection: 'સાચવેલ સંગ્રહ',
    savedProducts: 'સાચવેલ ઉત્પાદનો',
    savedProductsDesc: 'તમારી શોર્ટલિસ્ટ કરેલી લિસ્ટિંગને વ્યવસ્થિત રાખો જેથી તમે કિંમત, વેચાણકર્તા અને સ્થાનની ઝડપથી તુલના કરી શકો.',
    savedItems: 'સાચવેલી વસ્તુઓ',
    noSavedListings: 'હજી સુધી કોઈ સાચવેલી લિસ્ટિંગ નથી',
    noSavedDesc: 'કોઈપણ ઉત્પાદનને નજીક રાખવા માટે હૃદય પર ટેપ કરો.',
    featured: 'ફીચર્ડ',
    viewDetails: 'વિગતો જુઓ',
    listingUnavailable: 'લિસ્ટિંગ અનુપલબ્ધ',
    backToMarketplace: 'માર્કેટપ્લેસ પર પાછા ફરો',
    whatsappSeller: 'WhatsApp વેચાણકર્તા',
    saveListing: 'લિસ્ટિંગ સાચવો',
    share: 'શેર કરો',
    sellerRating: 'વેચાણકર્તા રેટિંગ',
    identitySignalsVerified: 'ઓળખ અને ચુકવણી સંકેતો ચકાસાયેલ',
    chat: 'ચેટ',
    searchChat: 'ચેટ શોધો...',
    now: 'હમણાં',
    online: 'ઓનલાઇન',
    today: 'આજે',
    writeMessage: 'સંદેશ લખો...',
    yourTrustedAccount: 'તમારું વિશ્વસનીય સ્થાનિક માર્કેટપ્લેસ એકાઉન્ટ.',
    authDesc: 'લિસ્ટિંગ સાચવો, વેચાણકર્તાઓને સંદેશ આપો, ઇન્વેન્ટરીનું સંચાલન કરો અને એવી પ્રતિષ્ઠા બનાવો જેના પર ખરીદદારો વિશ્વાસ કરી શકે.',
    welcomeBack: 'પાછા સ્વાગત છે',
    createAccount: 'એકાઉન્ટ બનાવો',
    authSubDesc: 'Firebase ઇમેઇલ/પાસવર્ડ અને Google પ્રમાણીકરણ જોડાયેલ છે.',
    fullName: 'પૂરું નામ',
    emailAddress: 'ઇમેઇલ સરનામું',
    password: 'પાસવર્ડ',
    signIn: 'સાઇન ઇન કરો',
    continueWithGoogle: 'Google સાથે ચાલુ રાખો',
    needAccount: 'શું તમારે એકાઉન્ટની જરૂર છે?',
    alreadyHaveAccount: 'શું તમારી પાસે પહેલેથી જ એકાઉન્ટ છે?',
    mobileNumber: 'મોબાઇલ નંબર',
    memberSince: 'સભ્યપદની શરૂઆત:',
  }
} as const;
